spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.206.195:3306/weather_community
    username: weather
    password: Weather1@

# secret 값은 특정 문자열을 Base64로 인코딩한 값 사용
# echo -n 'hello-my-real-name-is-kwanwoo-this-key-is-very-important-so-be-careful-thank-you' | openssl base64
# 1800000 30분
# 604800000 1주일
jwt:
  secret: aGVsbG8tbXktcmVhbC1uYW1lLWlzLWt3YW53b28tdGhpcy1rZXktaXMtdmVyeS1pbXBvcnRhbnQtc28tYmUtY2FyZWZ1bC10aGFuay15b3U=
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000
