spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/weather-db
    username: sa

jwt:
  secret: aGVsbG8tbXktcmVhbC1uYW1lLWlzLWt3YW53b28tdGhpcy1rZXktaXMtdmVyeS1pbXBvcnRhbnQtc28tYmUtY2FyZWZ1bC10aGFuay15b3U=
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000
