spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/weather-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # 페이지의 시작점을 0이 아닌 1로 설정(true)
  data:
    web:
      pageable:
        one-indexed-parameters: true

  sql:
    init:
      mode: always
#logging:
#  level:
#    root: debug


# secret 값은 특정 문자열을 Base64로 인코딩한 값 사용
# echo -n 'hello-my-real-name-is-kwanwoo-this-key-is-very-important-so-be-careful-thank-you' | openssl base64
# 1800000 30분
# 604800000 1주일
jwt:
  secret: aGVsbG8tbXktcmVhbC1uYW1lLWlzLWt3YW53b28tdGhpcy1rZXktaXMtdmVyeS1pbXBvcnRhbnQtc28tYmUtY2FyZWZ1bC10aGFuay15b3U=
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000

