spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true

  sql:
    init:
      mode: always


  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
