spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/weather-db
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # 페이지의 시작점을 0이 아닌 1로 설정(true)
  data:
    web:
      pageable:
        one-indexed-parameters: true

  sql:
    init:
      mode: always